site_name: microbit

# This text shows in the footer.
copyright: Digital Initiatives - Bendigo Kangan Institute

nav:
  # The Return to Portal item should always be the first item in the navigation.
  - Return to Portal: /

  # Add additional navigation below this point:
  - Menu:
    - Resources:
      - Introduction to Microbits and variables: pages/resources/01-intro-variables.md
      - Functions: pages/resources/02-functions.md
      - Event Loop: pages/resources/03-event-loop.md
      - Selection: pages/resources/04-selection-if-else-elif.md
      - Selection in Event Loop:  pages/resources/05-selection-event-loop.md
      - Loops and conditions:  pages/resources/06-loops.md
      - Lists: pages/resources/07-lists.md
    - Tasks:
      - Task 1 - Introduction to micro:bit: pages/tasks/task-1-intro-to-microbit.md
      - Task 2 - Variables: pages/tasks/task-2-variables.md
      - Task 3 - Functions: pages/tasks/task-3-functions.md
      - Task 4 - Functions, Parameters, and Returns: pages/tasks/task-4-functions-params-returns.md
      - Task 5 - Event Loop: pages/tasks/task-5-event-loop.md
      - Task 6 - Selection: pages/tasks/task-6-selection.md
      - Task 7 - Loops with Conditions: pages/tasks/task-7-loops-with-conditions.md
      - Task 8 - For Loops: pages/tasks/task-8-for-loops.md
      - Task 9 - Lists: pages/tasks/task-9-lists.md

# Do not touch anything below this line unless you know what you are doing.
theme:
  name: material
  palette:
    primary: purple
  features:
    - toc.integrate 
    - navigation.sections
    - navigation.path
    - navigation.footer
    - header.hide
    - content.code.copy
    - content.code.annotate

plugins:
  - enumerate-headings:
      increment_across_pages: true
      # Uncomment below if you would like to reset the table of contents numbering
      # after a certain page:
      restart_increment_after: 
        -  pages/tasks/task-1-intro-to-microbit.md

extra:
  generator: false

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

extra_css:
  - extra/style.css
