site_name: microbit

# This text shows in the footer.
copyright: Digital Initiatives - Bendigo Kangan Institute

nav:
  # The Return to Portal item should always be the first item in the navigation.
  - Return to Portal: /portal

  # Add additional navigation below this point:
  - Menu:
    - Resources:
      - Introduction to Microbits and variables: pages/resources/01-intro-variables.md
      - Functions: pages/resources/02-functions.md
      - Event Loop: pages/resources/03-event-loop.md
      - Selection: pages/resources/04-selection-if-else-elif.md
      - Selection in Event Loop:  pages/resources/05-selection-event-loop.md
    - Tasks:
      - Task 1 - Introduction to microbit: pages/tasks/task1

# Do not touch anything below this line unless you know what you are doing.
theme:
  name: material
  palette:
    primary: purple
  features:
    - toc.integrate 
    - navigation.sections
    - navigation.path
    - navigation.footer
    - header.hide
    - content.code.copy
    - content.code.annotate

plugins:
  - enumerate-headings:
      increment_across_pages: true
      # Uncomment below if you would like to reset the table of contents numbering
      # after a certain page:
      restart_increment_after: 
        -  pages/tasks/task1.md

extra:
  generator: false

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

extra_css:
  - extra/style.css
