site_name: Digital Initiatives MkDocs Portal

# This text shows in the footer.
copyright: Digital Initiatives - Bendigo Kangan Institute

site_url: https://robocoportal.netlify.app

# Do not touch anything below this line unless you knwo what you are doing.
nav:
  - Portal: index.md

theme:
  name: material
  palette:
    primary: deep purple
  features:
    - toc.integrate 
    - navigation.sections
    - navigation.path
    - navigation.footer
    - header.hide
    - content.code.copy
    - content.code.annotate

extra:
  generator: false

extra_css:
  - extra/style.css

plugins: []

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
