site_name: Digital Initiatives MkDocs Portal
site_url: https://robocoportal.netlify.app
nav:
  - Portal: index.md

theme:
  name: material
  palette:
    primary: deep purple
  features:
    - toc.integrate 
    - navigation.sections
    - navigation.path
    - navigation.footer
    - header.hide
    - content.code.copy
    - content.code.annotate

extra:
  generator: false
copyright: Digital Initiatives - Bendigo Kangan Institute

plugins: []

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
