site_name: Programming & Design
nav:
  - Python:
    - Resources:
      - Intro to Python & Edison: python/resources/python-edison-intro.md
    - Tasks:
      - Task 1 - Intro to Edison: python/tasks/task-1-intro-to-edison.md

  - Design:
    - Test: index.md
theme: readthedocs
extra_css:
  - extra/style.css
